version: '2'

services:
  redis:
    image: therickys93/wikiredis
    ports:
      - "6379:6379"
    networks:
      - backbone

  controller:
    image: therickys93/wikicontroller
    environment:
      - HOST=redis
    networks:
      - backbone

  proxy:
    image: therickys93/wikiproxy
    ports:
      - "80:80"
    networks:
      - backbone

  mediaserver:
    image: therickys93/wikimediaserver
    ports:
      - "8080:3000"
    networks:
      - backbone

networks:
  backbone:
    driver: bridge