version: '2'

services:
  redis:
    image: therickys93/wikiredis
    ports:
      - "6379:6379"
    networks:
      - backbone

  controller:
    image: therickys93/wikicontroller
    environment:
      - HOST=redis
    networks:
      - backbone

  proxy:
    image: therickys93/wikiproxy
    ports:
      - "80:80"
    networks:
      - backbone

  mediaserver:
    image: therickys93/wikimediaserver
    ports:
      - "3000:3000"
    networks:
      - backbone

  rediscommander:
    image: therickys93/wikirediscommander
    command: redis-commander --address 0.0.0.0 --port 8081 --redis-host redis
    ports:
      - "8081:8081"
    networks:
      - backbone

  server:
    image: therickys93/wikiserver
    ports:
      - "8080:8080"
    networks:
      - backbone

networks:
  backbone:
    driver: bridge