version: '2'

services:
  redis:
    build: wikiredis
    ports:
      - "6379:6379"
    networks:
      - backbone

  controller:
    build: wikicontroller
    depends_on:
      - redis
    environment:
      - HOST=redis
    networks:
      - backbone

  postgres:
    build: wikidatabase
    environment:
     - POSTGRES_PASSWORD=example

  data:
    build: wikidata
    environment:
      - FTP_SERVER=<your_server>
      - FTP_USERNAME=<your_username>
      - FTP_PASSWORD=<your_password>
      - REDIS=redis
    networks: 
      - backbone

  proxy:
    build: wikiproxy
    ports:
      - "80:80"
    networks:
      - backbone

  mediaserver:
    build: wikimediaserver
    environment:
      - WIKISERVER_PORT=8080
      - WIKISERVER_HOST=localhost
      - WIKISERVER_WOEID=716231
    ports:
      - "3000:3000"
    networks:
      - backbone

  rediscommander:
    build: wikirediscommander
    command: redis-commander --address 0.0.0.0 --port 8081 --redis-host redis
    ports:
      - "8081:8081"
    networks:
      - backbone

  server:
    build: wikiserver
    ports:
      - "8080:8080"
    networks:
      - backbone

networks:
  backbone:
    driver: bridge