version: '3'

services: 
  reg-srv:
    image: registry:latest
    ports:
      - 5000:5000
    volumes:
      - registry_database:/var/lib/registry
    deploy:
      placement:
        constraints:
          - node.hostname == node1
    networks:
      reg-net:
        aliases:
          - reg-serv
          
networks:
  reg-net:
    driver: overlay

volumes:
  registry_database:
    driver: local
